version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${STACK_VERSION}
    volumes:
      - /opt/elk/esdata/:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:${STACK_VERSION}
#    volumes:
#      - /opt/elk/kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:${STACK_VERSION}
    volumes:
      - /opt/elk/logstashdata:/usr/share/logstash/data
      - "./logstash_ingest_data/:/usr/share/logstash/ingest_data/"
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    user: root
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://elasticsearch:9200
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk

networks:
  elk:
    driver: bridge
